# Generated by Django 4.1.3 on 2022-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_categories_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(max_length=200, unique=True)),
                ('uuid', models.CharField(max_length=200)),
            ],
        ),
    ]
