# Generated by Django 4.1.3 on 2022-11-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_foodtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, unique=True)),
                ('book_author', models.CharField(max_length=200)),
                ('book_cover', models.ImageField(default=None, upload_to='books/')),
                ('book', models.FileField(default=None, upload_to='books/')),
                ('uuid', models.CharField(max_length=255)),
            ],
        ),
    ]
