# Generated by Django 4.1.3 on 2022-11-19 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 11, 19)),
        ),
    ]
