# Generated by Django 4.1.3 on 2022-11-20 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_users_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.CreateModel(
            name='Resturants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=11)),
                ('image', models.ImageField(default=None, upload_to='resturant/')),
                ('uuid', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(to='dashboard.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.users')),
            ],
        ),
    ]
